### ISSUE TITLE
To fix

### ISSUE THREAD

**Issue by EmileRolley** [CatalaLang/catala-website#30]
## TODOs

* [x] Add a `FrenchLaw` module.
* [x] Clean the `FrenchHousingBenefitsExample`.
* [x] Better error handling from the french_law.
* [x] Visualization page in small screen.
* [x] Center text in the presentation page for very small screen.
* [x] Fix code highlighting with the new fixed navbar
